name: Python application

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Install Python3
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install python3
